services:
  postgres:
    image: postgres:16
    container_name: web-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web
      POSTGRES_DB: web
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - uploads_data:/statics/images

volumes:
  postgres_data:
  uploads_data: